name: Dual AI Market Summary

on:
  schedule:
    - cron: '0 11 * * 1-5'  # 7 AM ET
    - cron: '0 21 * * 1-5'  # 5 PM ET
  workflow_dispatch:

jobs:
  generate-dual-ai-summary:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 📦 Install dependencies
      run: |
        pip install anthropic openai
        
    - name: 🤖 Generate dual AI summary
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python ai_newsletter.py
