name: AI Market Analysis

on:
  schedule:
    # Runs at 6:30 AM MST (12:30 PM UTC) every day
   # - cron: '30 12 * * *'
    # Runs at 5:30 PM MST (11:30 PM UTC next day) every day
 #   - cron: '30 23 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  market-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run AI Market Aggregator
      env:
        # Email Configuration
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        
        # API Keys
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        python ai_market_aggregator.py
    
    - name: Log completion
      run: |
        echo "✅ AI Market Analysis completed at $(date)"
