name: Clean Market Data Aggregator

on:
  schedule:
    # 7:00 AM ET (11:00 UTC) - Morning data collection
    - cron: '0 11 * * 1-5'
    # 5:00 PM ET (21:00 UTC) - Evening data collection  
    - cron: '0 21 * * 1-5'
  workflow_dispatch: # Manual trigger for testing

jobs:
  aggregate-market-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 📦 Install dependencies
      run: |
        pip install requests
        
    - name: 📊 Run clean market aggregator
      env:
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python clean_market_aggregator.py
